In [1]:
## Starting with Julia
α = 3

3

In [ ]:
α


In [3]:
# We can build mathematical functions in julia just like in R but not
# in Python

f(x) = x^2 + x*2 + 2

f (generic function with 1 method)

In [4]:
f(3)

17

    ### Variable Substituation
    #### In this we can just use $ to mark to the object or value we are referrring to.

In [6]:
name = "Mavez"
greetings = "Hello $name"
println(greetings)

Hello Mavez


In [7]:
μ = 3
println("The sin of $μ is $(sin(μ))")

The sin of 3 is 0.1411200080598672


### Numerical Types

##### Q1- Calculate power of 10 using standard integers and BigInts

In [9]:
number  = int64(2)
power = int64(10^2)
println("The power is now $power")

The power is now 100


In [8]:
10^2

100

In [15]:
ten = big(10)
10^19 # This will give random value as numbers exceed the floating 
# value

-8446744073709551616

In [16]:
ten^19 # This will work fine

10000000000000000000

### Complex 
##### Imaginary part with im

In [18]:
a = 7
c = (5 + .5im) * a


35.0 + 3.5im

##### Every thing is function in Julia

In [19]:
+(3+4)

7

In [20]:
# generic functions
//

// (generic function with 8 methods)

In [21]:
methods(//)

# 8 methods for generic function "//":
//(n::Integer,d::Integer) at rational.jl:15
//(x::Rational{T<:Integer},y::Integer) at rational.jl:16
//(x::Integer,y::Rational{T<:Integer}) at rational.jl:17
//(x::Rational{T<:Integer},y::Rational{T<:Integer}) at rational.jl:18
//(x::Complex{T<:Real},y::Real) at rational.jl:19
//(x::Real,y::Complex{T<:Real}) at rational.jl:20
//(x::Complex{T<:Real},y::Complex{T<:Real}) at rational.jl:23
//(X::AbstractArray{T,N},y::Number) at rational.jl:28

### List and numpy Arrays
###### ; hides the answer

In [22]:
l = [1,3,5]

3-element Array{Int64,1}:
 1
 3
 5

In [23]:
typeof(l)

Array{Int64,1}

In [ ]:
##### Q2- Create an array with different type of elements in it. 

In [24]:
arr = [1,3.55,-65]
## Promotes to float

3-element Array{Float64,1}:
   1.0 
   3.55
 -65.0 

In [30]:
arr1 = [1,"Hello"]
# Array with type Any

## double "" used to represent String


2-element Array{Any,1}:
 1       
  "Hello"

In [32]:
l = {3,4,[32,"Hello"]}

3-element Array{Any,1}:
 3            
 4            
  {32,"Hello"}

### Indexing
##### Julia works similarly to R interms of indentation

In [37]:
mav = [1,2,4,4,5,5,55,5,5]
mav[1:end]

9-element Array{Int64,1}:
  1
  2
  4
  4
  5
  5
 55
  5
  5

In [38]:
mav + mav

9-element Array{Int64,1}:
   2
   4
   8
   8
  10
  10
 110
  10
  10

In [44]:
num = [1,2,3]
push!(num,6)

4-element Array{Int64,1}:
 1
 2
 3
 6

In [45]:
#### To find all the methods associated with a type
methodswith(Array)

103-element Array{Method,1}:
 Message(a::Array{T,N}) at /Users/mavezsinghdabas/.julia/v0.3/ZMQ/src/ZMQ.jl:434                                                                        
 -(A::Array{T,N},B::SparseMatrixCSC{Tv,Ti<:Integer}) at sparse/sparsematrix.jl:650                                                                      
 -(A::SparseMatrixCSC{Tv,Ti<:Integer},B::Array{T,N}) at sparse/sparsematrix.jl:648                                                                      
 length(a::Array{T,N}) at array.jl:21                                                                                                                   
 copy!{T}(dest::Array{T,N},dsto::Integer,src::Array{T,N},so::Integer,N::Integer) at array.jl:51                                                         
 copy!{T}(dest::Array{T,N},src::Array{T,N}) at array.jl:57                                                                                              
 copy!(S::SharedArray{T,N},A::Array{T,N}) at sharedarray.jl:290                                                                                         
 msync{T}(A::Array{T,N}) at mmap.jl:6                                                                                                                   
 serialize(s,a::Array{T,N}) at serialize.jl:119                                                                                                         
 permutedims!{T,N}(P::Array{T,N},B::Union(SubArray{T,N,A<:DenseArray{T,N},I<:(Union(Int64,Range{Int64})...,)},DenseArray{T,N}),perm) at cartesian.jl:100
 unsafe_copy!{T}(dest::Array{T,N},dsto,src::Array{T,N},so,N) at array.jl:40                                                                             
 .\(A::SparseMatrixCSC{Tv,Ti<:Integer},B::Array{T,N}) at sparse/sparsematrix.jl:665                                                                     
 .\(A::Array{T,N},B::SparseMatrixCSC{Tv,Ti<:Integer}) at sparse/sparsematrix.jl:666                                                                     
 ⋮                                                                                                                                                      
 read!(from::IOBuffer,a::Array{T,N}) at iobuffer.jl:55                                                                                                  
 read!{T}(s::IOStream,a::Array{T,N}) at iostream.jl:192                                                                                                 
 read!{T}(s::AsyncStream,a::Array{T,N}) at stream.jl:657                                                                                                
 read!{T}(f::File,a::Array{T,N}) at fs.jl:219                                                                                                           
 read!{T}(f::File,a::Array{T,N},nel) at fs.jl:219                                                                                                       
 read!{T}(s::IO,a::Array{T,N}) at io.jl:126                                                                                                             
 +(A::SparseMatrixCSC{Tv,Ti<:Integer},B::Array{T,N}) at sparse/sparsematrix.jl:643                                                                      
 +(A::Array{T,N},B::SparseMatrixCSC{Tv,Ti<:Integer}) at sparse/sparsematrix.jl:645                                                                      
 reinterpret{T,S}(::Type{T},a::Array{S,N}) at array.jl:66                                                                                               
 reinterpret{T,S,N}(::Type{T},a::Array{S,N},dims::NTuple{N,Int64}) at array.jl:73                                                                       
 slicedim(A::Array{T,N},d::Integer,i::Integer) at array.jl:847                                                                                          
 sub{T,N}(A::Array{T,N},i::(Range{Int64},)) at subarray.jl:52

### Control flow 

In [46]:
total = 0
for i in 1:10 # Range object just like in R
    total += i
end
println("The sum total is $total")

The sum total is 55


In [47]:
[1:2:10]

5-element Array{Int64,1}:
 1
 3
 5
 7
 9